"""add personal email to recruit table

Revision ID: 184e6a3df64c
Revises: a2a493d1cc83
Create Date: 2020-10-13 15:39:00.773516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184e6a3df64c'
down_revision = 'a2a493d1cc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('personal_email_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'recruits', ['personal_email_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruits', type_='unique')
    op.drop_column('recruits', 'personal_email_address')
    # ### end Alembic commands ###
