"""Create migrations to delete id column 

Revision ID: 35a3a7d51f17
Revises: 7bb2e6fc8f49
Create Date: 2020-10-14 15:45:23.854301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a3a7d51f17'
down_revision = '7bb2e6fc8f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'id_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('id_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
