"""Create migrations to add cohort in alembic with a default

Revision ID: 61cbff913916
Revises: f415547e0fba
Create Date: 2020-10-14 14:10:20.148341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cbff913916'
down_revision = 'f415547e0fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('cohort', sa.String(), server_default='C25 Data Eng', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'cohort')
    # ### end Alembic commands ###
