"""Added recruit email address

Revision ID: 8bab4ed17853
Revises: a9f8380c492e
Create Date: 2020-10-14 12:03:28.413060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bab4ed17853'
down_revision = 'a9f8380c492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('personal_email_address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'personal_email_address')
    # ### end Alembic commands ###
